//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MomentumData
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MomentumEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MomentumEntities object using the connection string found in the 'MomentumEntities' section of the application configuration file.
        /// </summary>
        public MomentumEntities() : base("name=MomentumEntities", "MomentumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MomentumEntities object.
        /// </summary>
        public MomentumEntities(string connectionString) : base(connectionString, "MomentumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MomentumEntities object.
        /// </summary>
        public MomentumEntities(EntityConnection connection) : base(connection, "MomentumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StockDay> StockDays
        {
            get
            {
                if ((_StockDays == null))
                {
                    _StockDays = base.CreateObjectSet<StockDay>("StockDays");
                }
                return _StockDays;
            }
        }
        private ObjectSet<StockDay> _StockDays;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StockDays EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStockDays(StockDay stockDay)
        {
            base.AddObject("StockDays", stockDay);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MomentumModel", Name="StockDay")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StockDay : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StockDay object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="ticker">Initial value of the Ticker property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="open">Initial value of the Open property.</param>
        /// <param name="close">Initial value of the Close property.</param>
        /// <param name="high">Initial value of the High property.</param>
        /// <param name="low">Initial value of the Low property.</param>
        /// <param name="volume">Initial value of the Volume property.</param>
        /// <param name="dateStamp">Initial value of the DateStamp property.</param>
        public static StockDay CreateStockDay(global::System.Int32 id, global::System.String ticker, global::System.String name, global::System.Double open, global::System.Double close, global::System.Double high, global::System.Double low, global::System.Int32 volume, global::System.DateTime dateStamp)
        {
            StockDay stockDay = new StockDay();
            stockDay.Id = id;
            stockDay.Ticker = ticker;
            stockDay.Name = name;
            stockDay.Open = open;
            stockDay.Close = close;
            stockDay.High = high;
            stockDay.Low = low;
            stockDay.Volume = volume;
            stockDay.DateStamp = dateStamp;
            return stockDay;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ticker
        {
            get
            {
                return _Ticker;
            }
            set
            {
                OnTickerChanging(value);
                ReportPropertyChanging("Ticker");
                _Ticker = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ticker");
                OnTickerChanged();
            }
        }
        private global::System.String _Ticker;
        partial void OnTickerChanging(global::System.String value);
        partial void OnTickerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Open
        {
            get
            {
                return _Open;
            }
            set
            {
                OnOpenChanging(value);
                ReportPropertyChanging("Open");
                _Open = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Open");
                OnOpenChanged();
            }
        }
        private global::System.Double _Open;
        partial void OnOpenChanging(global::System.Double value);
        partial void OnOpenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Close
        {
            get
            {
                return _Close;
            }
            set
            {
                OnCloseChanging(value);
                ReportPropertyChanging("Close");
                _Close = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Close");
                OnCloseChanged();
            }
        }
        private global::System.Double _Close;
        partial void OnCloseChanging(global::System.Double value);
        partial void OnCloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double High
        {
            get
            {
                return _High;
            }
            set
            {
                OnHighChanging(value);
                ReportPropertyChanging("High");
                _High = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("High");
                OnHighChanged();
            }
        }
        private global::System.Double _High;
        partial void OnHighChanging(global::System.Double value);
        partial void OnHighChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Low
        {
            get
            {
                return _Low;
            }
            set
            {
                OnLowChanging(value);
                ReportPropertyChanging("Low");
                _Low = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Low");
                OnLowChanged();
            }
        }
        private global::System.Double _Low;
        partial void OnLowChanging(global::System.Double value);
        partial void OnLowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private global::System.Int32 _Volume;
        partial void OnVolumeChanging(global::System.Int32 value);
        partial void OnVolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateStamp
        {
            get
            {
                return _DateStamp;
            }
            set
            {
                OnDateStampChanging(value);
                ReportPropertyChanging("DateStamp");
                _DateStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateStamp");
                OnDateStampChanged();
            }
        }
        private global::System.DateTime _DateStamp;
        partial void OnDateStampChanging(global::System.DateTime value);
        partial void OnDateStampChanged();

        #endregion

    
    }

    #endregion

    
}
